---
- name: Collect Linux Server Info
  hosts: servers
  become: true
  gather_facts: true

  tasks:
    - name: Display hostname and Debian version
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }} running {{ ansible_distribution }} {{ ansible_distribution_version }}!"

    - name: Touch File
      ansible.builtin.copy:
        dest: /tmp/ansible_was_here.txt
        content: "{{ inventory_hostname }}! Ansible ran successfully on {{ ansible_date_time.date }}.\n"
        mode: "0644"
