---
- name: Generate Proxmox Inventory
  hosts: pve
  gather_facts: false
  vars:
    inventory_file: inventory/proxmox_inventory.ini
  tasks:
    - name: Get Proxmox VM facts
      community.general.proxmox_kvm:
        api_host: "{{ ansible_host }}"
        api_user: "{{ proxmox_api_user | default('root@pam') }}"
        api_password: "{{ proxmox_api_password | default(omit) }}"
        api_token_id: "{{ proxmox_api_token_id | default(omit) }}"
        api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
        validate_certs: false
      register: kvm_facts

    - name: Get Proxmox LXC facts
      community.general.proxmox:
        api_host: "{{ ansible_host }}"
        api_user: "{{ proxmox_api_user | default('root@pam') }}"
        api_password: "{{ proxmox_api_password | default(omit) }}"
        api_token_id: "{{ proxmox_api_token_id | default(omit) }}"
        api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
        validate_certs: false
        type: lxc
      register: lxc_facts

    - name: Generate inventory file
      template:
        src: templates/proxmox_inventory.ini.j2
        dest: "{{ inventory_file }}"
      vars:
        kvms: "{{ kvm_facts.results | map(attribute='vms') | flatten }}"
        lxcs: "{{ lxc_facts.results | map(attribute='containers') | flatten }}"
