---
- name: Generate Proxmox Inventory
  hosts: pve
  gather_facts: false
  vars:
    inventory_file: inventory/proxmox_inventory.ini
  tasks:
    - name: Get Proxmox VM facts
      community.general.proxmox_kvm:
        proxmox_host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "" # Assuming SSH key authentication
        validate_certs: false
      register: kvm_facts

    - name: Get Proxmox LXC facts
      community.general.proxmox_lxc:
        proxmox_host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "" # Assuming SSH key authentication
        validate_certs: false
      register: lxc_facts

    - name: Generate inventory file
      template:
        src: templates/proxmox_inventory.ini.j2
        dest: "{{ inventory_file }}"
      vars:
        kvms: "{{ kvm_facts.results | map(attribute='vms') | flatten }}"
        lxcs: "{{ lxc_facts.results | map(attribute='containers') | flatten }}"
